module.exports = [{
    id:"1",
    label:"四川省",
    children:[
        {
            id:"2",
            label:"成都市",
            parentId:"1",
            children:[
                {
                    id:"3",
                    label:"高新区",
                    parentId:"2",
                },
                {
                    id:"23471",
                    label:"都江堰市",
                    parentId:"2",
                },
                {
                    id:"23480",
                    label:"崇州市",
                    parentId:"2",
                },
            ]
        },
        {
            id:"6",
            label:"眉山市",
            parentId:"1", 
            children:[
                {
                    id:"23387",
                    label:"仁寿县",
                    parentId:"6"
                },
                {
                    id:"23521",
                    label:"东坡区",
                    parentId:"6"
                }
            ]
        }

    ]
},
    {
        id:"7",
        label:"重庆市",
        children:[
            {
                id:"34767",
                label:"沙坪坝区",
                parentId:"7",
                children:[
                    {
                        id:"34768",
                        label:"回龙坝镇",
                        parentId:"34767"
                    },
                    {
                        id:"34769",
                        label:"歌乐山街道",
                        parentId:"34767"
                    }
                ]
            },
            {
                id:"34788",
                label:"阳土家族苗族自治区",
                parentId:"7",
                children:[
                    {
                        id:"34789",
                        label:"昱地乡",
                        parentId:"34788"
                    },
                    {
                        id:"34790",
                        label:"两里乡",
                        parentId:"34788"
                    }
                ]
            }
        ] 
    }
]
// module.exports = {
//     CityList: CityList
// }