/**
 * 模拟后台返回的城市三级数据结构
 */
let cityData=[
  {
    id:'1',
    label:'四川省',
    children:[
      {
        id:'2',
        label:'成都市',
        parentId:'1',
        children:[
          {
            id:'3',
            label:'高新区',
            parentId:'2'
          },
          {
            id:'4',
            label:'武侯区',
            parentId:'2'
          },
          {
            id:'5',
            label:'金牛区',
            parentId:'2'
          },
          {
            id:'6',
            label:'双流区',
            parentId:'2'
          }
        ]
      },
      {
        id:'3',
        label:'高新区',
        parentId:'1',
        children:[
          {
            id:'7',
            label:'环球中心',
            parentId:'3'
          }
        ]
      }
    ]
  },
  {
    id:'11',
    label:'重庆市',
    children:[
      {
        id:'12',
        label:'沙坪坝',
        parentId:'11',
        children:[
          {
            id:'13',
            label:'回龙镇',
            parentId:'12'
          },
          {
            id:'18',
            label:'xx镇',
            parentId:'12'
          }
        ]
      },
      {
        id:'14',
        label:'丰都县',
        parentId:'11',
        children:[
          {
            id:'15',
            label:'双路镇',
            parentId:'14'
          }
        ]
      }
    ]
  }
]


module.exports = {
  cityData
}